name: 'Setup Enviroment'
description: 'Greet someone'
inputs:
  php-versions:
    description: 'Version of PHP to setup'
    required: false
    default: '7.3'
  php-extensions:
    description: 'Additional php extensions required'
    required: false
    default: 'mbstring, ds'
  php-ini-values:
    description: 'ini values to go to php'
    required: false
    default: ''
  composer-github-oauth:
    description: 'oauth key to use for composer and github'
    required: true
    default: ''  

outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - name: Cache node_modules directory
      uses: actions/cache@v2
      id: node_modules-cache
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('**/package.json') }}-${{ hashFiles('**/package-lock.json') }}
    - name: Install NPM packages
      if: steps.node_modules-cache.outputs.cache-hit != 'true'
      run: npm ci
    - name: Build frontend
      run: npm run development
    - name: Install PHP with extensions
      uses: shivammathur/setup-php@v2
      with:
        coverage: "none"
        tools: "composer:v2"
        extensions: "${{ inputs.php-extensions }}"
        ini-values: "${{ inputs.php-ini-values }}"
        php-version: "${{ inputs.php-versions }}"
      env:
        GITHUB_TOKEN: ${{ inputs.composer-github-oauth }}
    - name: Get Composer Cache Directory 2
      id: composer-cache
      run: |
        echo "name=dir::$(composer config cache-files-dir)"  >> $GITHUB_OUTPUT
    - uses: actions/cache@v2
      id: actions-cache
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-
    - name: Cache PHP dependencies
      uses: actions/cache@v2
      id: vendor-cache
      with:
        path: vendor
        key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}
    - name: Install Dependencies
      if: steps.vendor-cache.outputs.cache-hit != 'true'
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs
